version: '3'

services:
  db:
    container_name: postgresyprod
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - .:/data/postgres
    environment:
      POSTGRES_USER: yprod
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: yprod
